series: jammy

saas:
  grafana-dashboards:
    url: admin/cos.grafana-dashboards
  logging:
    url: admin/cos.loki-logging
  prometheus-scrape:
    url: admin/cos.prometheus-scrape
  prometheus-receive-remote-write:
    url: admin/cos.prometheus-receive-remote-write

applications:
  ubuntu:
    charm: ubuntu
    constraints: instance-type=t2.large root-disk=100G spaces=internal-space
    num_units: 1
    bindings:
      "": internal-space

  grafana-agent:
    charm: grafana-agent
    channel: latest/edge
    bindings:
      "": internal-space

relations:
- - ubuntu:juju-info
  - grafana-agent
- - grafana-agent
  - grafana-dashboards
- - grafana-agent
  - prometheus-receive-remote-write
- - grafana-agent
  - logging
