series: jammy

saas:
  grafana-dashboards:
    url: admin/cos.grafana-dashboards
  logging:
    url: admin/cos.loki-logging
  prometheus-scrape:
    url: admin/cos.prometheus-scrape
  prometheus-receive-remote-write:
    url: admin/cos.prometheus-receive-remote-write

  mysql-database:
    url: admin/mysql-k8s.mysql-database


applications:
  mysql-test-app:
    charm: ./mysql-test-app/mysql-test-app_ubuntu-22.04-amd64_ubuntu-20.04-amd64.charm
    constraints: instance-type=t2.medium root-disk=100G spaces=internal-space
    num_units: 1
    bindings:
      "": internal-space

  ubuntu:
    charm: ubuntu
    constraints: instance-type=t2.large root-disk=100G spaces=internal-space
    num_units: 1
    bindings:
      "": internal-space

  mysql-router:
    charm: mysql-router
    channel: dpe/edge
    bindings:
      "": internal-space
#    offers:
#      mysql-router-backend:
#        endpoints:
#          - backend-database

  grafana-agent:
    charm: grafana-agent
    channel: latest/edge
    bindings:
      "": internal-space

relations:
- - ubuntu
  - grafana-agent
- - grafana-agent
  - grafana-dashboards
- - grafana-agent
  - prometheus-receive-remote-write
- - grafana-agent
  - logging

- - mysql-test-app:database
  - mysql-router
- - mysql-router:backend-database
  - mysql-database
